WIP Add project-plan.md
DIN-Foundation/bsc-ntnu-2021 pull request #5
Opened 2021-01-18 13:48 UTC by Arxcis

Writing the initial project plan. 

**Deadline: 2021-02-01 @ 23:59**

Fixes #4

2021-01-25 11:38 UTC, Arxcis commented
> Looks like a good start to me

Great :+1: I am following a standard template for the project plan, given to the students by NTNU.

I finally found a way to mark the Pull Request as a Draft. This will be turned in the "ready-for-review" pull request, when the implementation is considered complete.

2021-01-25 14:48 UTC, Arxcis commented on project-plan.md
> +**@TODO Make list of ledgers to investigate**
@vongohren To limit the scope of the project, I think we should come up with a list of wallets and ledgers to focus on for the interoperability investigation.

2021-01-25 14:59 UTC, Arxcis commented on project-plan.md
> +**@TODO Make list of ledgers to investigate**
Moved to issue #7

2021-01-26 14:11 UTC, vongohren requested changes
Some comments and minor changes

![](https://media2.giphy.com/media/Ll9fCTNWC41rsbuqxk/giphy.gif)

2021-01-26 14:11 UTC, vongohren commented on project-plan.md
> +The project is looking at interoperability of the current SSI-infrastructure. More specifically interoperability between wallets, and interoperability between ledgers.
did methods is more right word

2021-01-26 14:11 UTC, vongohren commented on project-plan.md
> +- Issuing a credential to a ledger
You dont issue a credential to a ledger :P You issue to a holder, who has a DID, on whatever ledger

2021-01-26 14:11 UTC, vongohren commented on project-plan.md
> +- Hold the credential in a wallet
I would try to just make sure that wallet does not point back to app, a wallet can be an agent, and just some simple CLI methods towards that agent. To avoid too much UI stuff

2021-01-26 14:11 UTC, vongohren commented on project-plan.md
> +- Proove ownership of a credential to a 3rd party.
Try to use the terminology of the trust triangle.
Issuer, Holder and verifier.

Holder wants to showcase a credential to a verifier. The verifier can do a selective disclosue request: https://veramo.io/docs/fundamentals/selective_disclosure. I do think this is veramo words, and not nessecareily a standard word. But it might come from the token exchange and oAuth world :D

2021-01-26 14:11 UTC, vongohren commented on project-plan.md
> +*Disclaimer: The BSc has no affiliation with Statens Vegvesen at the moment of writing, and the story below is pure fantasy.*
Good stuff, the whole user story

2021-01-26 14:11 UTC, vongohren commented on project-plan.md
> +- A comparison matrix of ledger interoperability
You might want to have a small research round to see what is worth doing matrices on, or leaving this field a bit open while you journey through the space.

Suddenly you can have something that is worth a comparison matrix

2021-01-26 14:11 UTC, vongohren commented on project-plan.md
> +### Developer rules
:D Great rules

2021-01-26 14:11 UTC, vongohren commented on project-plan.md
> +- Rule 5: Log all hours in Toggl under these 5 categories: [Meeting, Organizing, Writing, Coding, Researching]
WHere is this request coming from? Just personal insight?

2021-01-26 14:11 UTC, vongohren commented on project-plan.md
> +The project is loosely driven forward by the Kanban framework. To keep track of progress in a Kanban project the Kanban board is essential. See the board here: https://github.com/DIN-Foundation/bsc-n
One thing that you need to reflect on, is how and when do you prioritize the tasks. And how do you capture ideas. And is there any specific need for a task to be able to move to do?

2021-01-26 14:11 UTC, vongohren commented on project-plan.md
> +### Risk 1: Proof-of-concept app development-cost unpredictability
Should we define actionpoints if the risk becomes clear?

2021-01-26 14:42 UTC, Arxcis commented on project-plan.md
> +1. Interoperability between different ledgers - where DIDs and VCs are stored.
Should have been resolved in ef1930a

2021-01-26 14:48 UTC, Arxcis commented on project-plan.md
> +See https://www.din.foundation/ for more info.
Addressed in e6bde3a

2021-01-26 14:52 UTC, Arxcis commented on project-plan.md
> +The project is developed within the field of Self-sovereign-identity, aka SSI.
Addressed in b4d0f1d

2021-01-27 13:48 UTC, Arxcis commented on project-plan.md
> +The project is looking at interoperability of the current SSI-infrastructure. More specifically interoperability between wallets, and interoperability between ledgers.
Addressed in 5099505

2021-01-27 13:48 UTC, Arxcis commented on project-plan.md
> +- Issuing a credential to a ledger
Addressed in 5099505

2021-01-27 13:49 UTC, Arxcis commented on project-plan.md
> +- Hold the credential in a wallet
Addressed in 5099505

2021-01-27 13:52 UTC, Arxcis commented on project-plan.md
> +- Hold the credential in a wallet
@vongohren, I am still struggling with the difference between wallet and agent.

Here is my thinking:
- An agent controls a DID.
- A wallet holds credentials, but may also hold agents.
- In many wallets the agent is not inside the wallet, but somewhere in the cloud.
- The wallet then acts as a frontend to the agent.
- The wallet is just the human interface to the entire SSI-infrastructure, agents, credentials, and the lot.

2021-01-27 13:55 UTC, Arxcis commented on project-plan.md
> +*Disclaimer: The BSc has no affiliation with Statens Vegvesen at the moment of writing, and the story below is pure fantasy.*
Addressed in 5099505

2021-01-27 13:55 UTC, Arxcis commented on project-plan.md
> +- Proove ownership of a credential to a 3rd party.
Addressed in 5099505

2021-01-27 13:56 UTC, Arxcis commented on project-plan.md
> +*Disclaimer: The BSc has no affiliation with Statens Vegvesen at the moment of writing, and the story below is pure fantasy.*
Good :smile:

2021-01-27 13:58 UTC, Arxcis commented on project-plan.md
> +- Rule 5: Log all hours in Toggl under these 5 categories: [Meeting, Organizing, Writing, Coding, Researching]
Yes :+1:  Explanation given in 3ddc188

2021-01-27 14:00 UTC, Arxcis commented on project-plan.md
> +### Risk 1: Proof-of-concept app development-cost unpredictability
Yes. That is definitely a **@TODO** :+1:

2021-01-27 21:28 UTC, vongohren commented on project-plan.md
> +- Hold the credential in a wallet
This might help you on the direction: https://www.evernym.com/blog/hyperledger-aries/

2021-02-01 16:26 UTC, merged